### ISSUE TITLE
Lora merging on clip-vit-base with lora

### ISSUE THREAD

**Issue by DennisTang2000** [tanganke/fusion_bench#27]
Hello,

How would you run the commands to evaluate clip-vit-base with LoRA? and also how would you merge them together? Like if I want to simple average merge all clip-vit lora?

Specifically, could you provide an example modelpool config file that could merge the models that produced these results [here](https://github.com/tanganke/fusion_bench/blob/main/docs/modelpool/images/clip-vit-base-patch16_full%26lora%26l-lora.png)

Edit - in this [notebook](https://colab.research.google.com/drive/1JYPBdERSRU8irM859v0mMU8yU2hBGyFh?usp=sharing), I have loaded in your trained SUN397 LoRA as you show in [here](https://github.com/tanganke/fusion_bench/blob/b894b2b428b0fb606ce24a0247ada1e4b371a819/docs/modelpool/clip_vit.md), and if you print all the B keys, it is all 0, indicating a new lora (B*A will also be all 0), so the LoRA won't load correctly. 

Thanks

**Comment by tanganke** [comment]
A helper function to load LoRA models can be found at 

https://github.com/tanganke/fusion_bench/blob/b894b2b428b0fb606ce24a0247ada1e4b371a819/fusion_bench/models/linearized/vision_model.py#L51-L53

Because we setup the LoRA models on type `CLIPVisionTransformer` instead of `CLIPVisionModel`. 

https://github.com/tanganke/fusion_bench/blob/0d38365cb788b515749aa51d3b0de6d88da117a7/fusion_bench/method/classification/clip_finetune.py#L235-L250

This is useful when you load clip model using `CLIPModel.from_pretrained`.

Therefore, a model can be defined as

```yaml
_target_: fusion_bench.modelpool.CLIPVisionModelPool

models:
  sun397:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_sun397_lora-16

processor:
  _target_: transformers.CLIPProcessor.from_pretrained
  pretrained_model_name_or_path: openai/clip-vit-base-patch32

train_datasets: null
test_datasets: null
```

To evaluate this model on eight downstream task:

```bash
fusion_bench \
modelpool=... \
method=dummy \
taskpool=CLIPVisionModelTaskPool/clip-vit-classification_TA8_B16
```

**Comment by tanganke** [comment]
By loading models in the above way, the parameters are usually merged element-wisely. For example, using `method=simple_average` will return a `PeftModel` with $\theta_A = Avg(\theta_A^{(1)}, \theta_A^{(2)}, ..., \theta_A^{(N)})$. 

If you want to merge $BA$ instead of $B$ and $A$ separately, you may need another helper function to load the LoRA models and merge the adapters before merging, such as:

```python
 def load_merged_lora_vision_model_hf(base_model_name: str, peft_name: str): 
     model = CLIPVisionModel.from_pretrained(base_model_name).vision_model 
     return PeftModel.from_pretrained(model, peft_name, is_trainable=True).merge_and_unload()
```

Another way is to import the fusion algorithm and use it in your own code. For example:

```python
from fusion_bench.method import TaskArithmeticAlgorithm
from fusion_bench.modelpool import BaseModelPool

pretrained_model = ....
model_1 = .... 
model_2 = ....

modelpool = BaseModelPool({
  '_pretrained_': pretrained_model, 'model_1': model_1, 'model_2': model_2
})
merged_model = TaskArithmeticAlgorithm(scaling_factor=0.3).run(modelpool)
```

It's important that some method modifies the models in the model pool in-place.

**Comment by tanganke** [comment]
Updated documentation and `load_lora_vision_model_hf` in pull request #29

**Comment by DennisTang2000** [comment]
`_target_: fusion_bench.modelpool.CLIPVisionModelPool

models:
  _pretrained_:
    _target_: fusion_bench.models.linearized.vision_model.load_fft_vision_model_hf
    model_name: openai/clip-vit-base-patch16
  sun397:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_sun397_lora-16
  cars:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_stanford-cars_lora-16
  resisc45:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_resisc45_lora-16
  eurosat:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_eurosat_lora-16
  svhn:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_svhn_lora-16
  gtsrb:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_gtsrb_lora-16
  mnist:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_mnist_lora-16
  dtd:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_dtd_lora-16

processor:
  _target_: transformers.CLIPProcessor.from_pretrained
  pretrained_model_name_or_path: openai/clip-vit-base-patch16

train_datasets: null
test_datasets: null`

Would this be the correct modelpool yaml for task-arithmetic?

**Comment by tanganke** [comment]
```yaml
_target_: fusion_bench.modelpool.CLIPVisionModelPool

models:
  _pretrained_:
    _target_: fusion_bench.models.linearized.vision_model.load_fft_vision_model_hf
    model_name: openai/clip-vit-base-patch16
  sun397:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_sun397_lora-16
    merge_and_unload: true
  cars:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_stanford-cars_lora-16
    merge_and_unload: true
  resisc45:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_resisc45_lora-16
    merge_and_unload: true
  eurosat:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_eurosat_lora-16
    merge_and_unload: true
  svhn:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_svhn_lora-16
    merge_and_unload: true
  gtsrb:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_gtsrb_lora-16
    merge_and_unload: true
  mnist:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_mnist_lora-16
    merge_and_unload: true
  dtd:
    _target_: fusion_bench.models.linearized.vision_model.load_lora_vision_model_hf
    base_model_name: openai/clip-vit-base-patch16
    peft_name: tanganke/clip-vit-base-patch16_dtd_lora-16
    merge_and_unload: true

processor:
  _target_: transformers.CLIPProcessor.from_pretrained
  pretrained_model_name_or_path: openai/clip-vit-base-patch16

train_datasets: null
test_datasets: null
```

The configuration is basically correct, but there are a few minor errors:

1. you should use '_target_' instead of 'target' to specify the full name of the Python class.
2. "_pretrained_" is a special model name for a pre-trained model.
3. The pre-trained model has the type of `CLIPVisionTransformer`. For task arithmetic, the fine-tuned models should have the same architecture as the pre-trained model, unless you use a LoRA model initialized from the pre-trained model. So the Lora models need to be merged and unload Lora adapters.
